const API = location.port === "8001" ? "" : "http://127.0.0.1:8001";
let LANG = "en", LAST = null;
const $ = (id) => document.getElementById(id);

const I18N = {
en: {skip:"Skip to main content",sra:"Screen Reader Access",lang_more:"More languages",nav_home:"Home",nav_check:"Check a Claim",nav_report:"Assessment Report",nav_learn:"Investor Education",nav_help:"Helpline",ticker:"<strong>Notice:</strong> No one can guarantee market returns. Verify registration on SEBI / SCORES / NSE before transferring money. This portal gives education only — never investment advice.",crumb:"Home / Investor Resilience / Claim Assessment",h1:"Online Claim Assessment Facility",intro:"Paste the text of any investment tip, message, or video caption received on WhatsApp, Telegram, YouTube or Instagram. The facility examines whether the content is <strong>educating</strong> you or <strong>selling</strong> to you, states what evidence supports it, and explains the concept in plain words with a steady-vs-hype illustration.",form_title:"Application Form — Claim Details",form_label:"Text of claim / tip / caption",req:"(required)",form_hint:"Do not enter OTPs, bank passwords, or full account numbers. Only the claim text is needed.",btn_check:"Submit for assessment",btn_speak:"Listen to explanation",btn_clear:"Reset form",rep_title:"Assessment Report",empty:"No assessment generated yet. Acknowledgement number will appear here after submission.",loading:"Assessment in progress…",th_class:"Classification",th_ev:"Evidence level",th_mean:"Plain-language meaning",th_sim:"Consequence illustration (₹5,000/month × 12)",th_sig:"Detected signals",disclaimer:"Disclaimer: computer-generated educational assessment, not investment advice or a legal finding. Verify independently on SEBI / SCORES / NSE before acting.",learn_title:"Investor education",learn1:"What is NAV — per-share value of a mutual fund, changes daily.",learn2:"SIP — a fixed monthly habit; compounding rewards patience, not tips.",learn3:"Volatility — prices move up and down; guaranteed returns do not exist.",learn4:"Grievance — lodge complaints on SCORES; check nominee and IEPF status.",help_title:"Helpline",news_title:"What is new",news1:"Check tip-group screenshots before forwarding.",news2:"Nominee registration now mandatory for demat.",news3:"Unclaimed dividends recoverable via IEPF.",links_title:"Related links",hist_title:"Previous assessments",hist_empty:"None on this device yet.",footer:"Content owned and maintained by SANGYAN hackathon team for demonstration. Source registries: SEBI · NSE · SCORES.",f_acc:"Accessibility",f_terms:"Terms of Use",f_priv:"Privacy (no PII collected)",f_upd:"Last updated: Oct 2026"},
hinglish: {skip:"Main content par jayein",sra:"Screen Reader Access",lang_more:"Aur bhashayein",nav_home:"Home",nav_check:"Dawa Check Karein",nav_report:"Assessment Report",nav_learn:"Niveshak Shiksha",nav_help:"Helpline",ticker:"<strong>Suchna:</strong> Bazaar me pakke munafe ki guarantee koi nahi de sakta. Paisa bhejne se pehle SEBI / SCORES / NSE par registration verify karein. Yeh portal sirf shiksha deta hai — salah nahi.",crumb:"Home / Niveshak Suraksha / Dawa Mulyankan",h1:"Online Dawa Mulyankan Suvidha",intro:"WhatsApp, Telegram, YouTube ya Instagram par mile kisi bhi tip, message ya video caption ka text paste karein. Yeh suvidha batayegi ki content aapko <strong>sikha</strong> raha hai ya <strong>bech</strong> raha hai, iske peeche kya saboot hai, aur iska seedha-saadha matlab kya hai.",form_title:"Aavedan Form — Dawe ka Vivaran",form_label:"Dawe / tip / caption ka text",req:"(zaroori)",form_hint:"OTP, bank password ya poora account number na likhein. Sirf dawe ka text chahiye.",btn_check:"Mulyankan ke liye bhejein",btn_speak:"Samjhauta sunein",btn_clear:"Form saaf karein",rep_title:"Mulyankan Report",empty:"Abhi koi mulyankan nahi hua. Bhejne ke baad yahan report aayegi.",loading:"Mulyankan chal raha hai…",th_class:"Vargikaran",th_ev:"Saboot ka star",th_mean:"Seedhe shabdon me arth",th_sim:"Parinaam udaharan (₹5,000/mahina × 12)",th_sig:"Pakde gaye sanket",disclaimer:"Disclaimer: computer se bani shiksha report, salah ya kanooni faisla nahi. Kaam karne se pehle SEBI / SCORES / NSE par khud verify karein.",learn_title:"Niveshak shiksha",learn1:"NAV kya hai — mutual fund ke ek hisse ki keemat, roz badalti hai.",learn2:"SIP — har mahine ki aadat; compounding dhairya ka phal deta hai, tip ka nahi.",learn3:"Volatility — keemat upar-neeche hoti hai; pakke munafe hote hi nahi.",learn4:"Shikayat — SCORES par shikayat karein; nominee aur IEPF sthiti dekhein.",help_title:"Helpline",news_title:"Naya kya hai",news1:"Forward karne se pehle tip-group screenshot check karein.",news2:"Demat ke liye nominee ab anivarya hai.",news3:"IEPF se be-daawa dividend wapas mil sakta hai.",links_title:"Sambandhit link",hist_title:"Pichhle mulyankan",hist_empty:"Is device par abhi koi nahi.",footer:"Samagri pradarshan hetu SANGYAN hackathon team dwara. Source: SEBI · NSE · SCORES.",f_acc:"Accessibility",f_terms:"Upp yog shartein",f_priv:"Privacy (koi PII nahi)",f_upd:"Update: Oct 2026"},
hi: {skip:"मुख्य सामग्री पर जाएं",sra:"स्क्रीन रीडर एक्सेस",lang_more:"अन्य भाषाएँ",nav_home:"मुख्य पृष्ठ",nav_check:"दावा जांचें",nav_report:"मूल्यांकन रिपोर्ट",nav_learn:"निवेशक शिक्षा",nav_help:"हेल्पलाइन",ticker:"<strong>सूचना:</strong> बाज़ार में पक्के मुनाफे की गारंटी कोई नहीं दे सकता। पैसे भेजने से पहले SEBI / SCORES / NSE पर पंजीकरण सत्यापित करें। यह पोर्टल केवल शिक्षा देता है — सलाह नहीं।",crumb:"मुख्य पृष्ठ / निवेशक सुरक्षा / दावा मूल्यांकन",h1:"ऑनलाइन दावा मूल्यांकन सुविधा",intro:"WhatsApp, Telegram, YouTube या Instagram पर मिले किसी भी टिप, संदेश या वीडियो कैप्शन का पाठ चिपकाएं। यह सुविधा बताएगी कि सामग्री आपको <strong>सिखा</strong> रही है या <strong>बेच</strong> रही है, इसके पीछे क्या प्रमाण है, और इसका सीधा अर्थ क्या है।",form_title:"आवेदन प्रपत्र — दावे का विवरण",form_label:"दावे / टिप / कैप्शन का पाठ",req:"(आवश्यक)",form_hint:"OTP, बैंक पासवर्ड या पूरा खाता नंबर न लिखें। केवल दावे का पाठ चाहिए।",btn_check:"मूल्यांकन हेतु भेजें",btn_speak:"व्याख्या सुनें",btn_clear:"प्रपत्र साफ़ करें",rep_title:"मूल्यांकन रिपोर्ट",empty:"अभी कोई मूल्यांकन नहीं हुआ। भेजने के बाद रिपोर्ट यहाँ दिखेगी।",loading:"मूल्यांकन प्रगति पर है…",th_class:"वर्गीकरण",th_ev:"प्रमाण स्तर",th_mean:"सरल भाषा में अर्थ",th_sim:"परिणाम उदाहरण (₹5,000/माह × 12)",th_sig:"पकड़े गए संकेत",disclaimer:"अस्वीकरण: कंप्यूटर-निर्मित शैक्षणिक मूल्यांकन, निवेश सलाह या विधिक निष्कर्ष नहीं। कार्रवाई से पहले SEBI / SCORES / NSE पर स्वयं सत्यापित करें।",learn_title:"निवेशक शिक्षा",learn1:"NAV क्या है — म्यूचुअल फंड के एक हिस्से की कीमत, रोज़ बदलती है।",learn2:"SIP — हर महीने की आदत; चक्रवृद्धि धैर्य का फल देती है, टिप का नहीं।",learn3:"उतार-चढ़ाव — कीमत ऊपर-नीचे होती है; पक्का मुनाफा होता ही नहीं।",learn4:"शिकायत — SCORES पर शिकायत करें; नामांकन और IEPF स्थिति देखें।",help_title:"हेल्पलाइन",news_title:"नया क्या है",news1:"फॉरवर्ड करने से पहले टिप-ग्रुप स्क्रीनशॉट जांचें।",news2:"डीमैट हेतु नामांकन अब अनिवार्य है।",news3:"IEPF से बेदावा लाभांश वापस मिल सकता है।",links_title:"संबंधित लिंक",hist_title:"पिछले मूल्यांकन",hist_empty:"इस डिवाइस पर अभी कोई नहीं।",footer:"प्रदर्शन हेतु सामग्री SANGYAN हैकथॉन टीम द्वारा। स्रोत: SEBI · NSE · SCORES।",f_acc:"सुगम्यता",f_terms:"उपयोग की शर्तें",f_priv:"गोपनीयता (कोई PII नहीं)",f_upd:"अद्यतन: अक्तू 2026"},
mr: {skip:"मुख्य मजकुराकडे जा",sra:"स्क्रीन रीडर अ‍ॅक्सेस",lang_more:"इतर भाषा",nav_home:"मुख्यपृष्ठ",nav_check:"दावा तपासा",nav_report:"मूल्यमापन अहवाल",nav_learn:"गुंतवणूकदार शिक्षण",nav_help:"हेल्पलाइन",ticker:"<strong>सूचना:</strong> बाजारात खात्रीशीर परताव्याची हमी कोणीही देऊ शकत नाही. पैसे पाठवण्यापूर्वी SEBI / SCORES / NSE वर नोंदणी तपासा. हे पोर्टल फक्त शिक्षण देते — सल्ला नाही.",crumb:"मुख्यपृष्ठ / गुंतवणूकदार सुरक्षा / दावा मूल्यमापन",h1:"ऑनलाइन दावा मूल्यमापन सुविधा",intro:"WhatsApp, Telegram, YouTube किंवा Instagram वरील कोणत्याही टीप, संदेश किंवा व्हिडिओ कॅप्शनचा मजकूर चिकटवा. ही सुविधा सांगेल की मजकूर तुम्हाला <strong>शिकवत</strong> आहे की <strong>विकत</strong> आहे, त्यामागे काय पुरावा आहे आणि त्याचा साधा अर्थ काय आहे.",form_title:"अर्ज — दाव्याचा तपशील",form_label:"दावा / टीप / कॅप्शनचा मजकूर",req:"(आवश्यक)",form_hint:"OTP, बँक पासवर्ड किंवा पूर्ण खाते क्रमांक लिहू नका. फक्त दाव्याचा मजकूर हवा आहे.",btn_check:"मूल्यमापनासाठी पाठवा",btn_speak:"स्पष्टीकरण ऐका",btn_clear:"अर्ज साफ करा",rep_title:"मूल्यमापन अहवाल",empty:"अद्याप कोणतेही मूल्यमापन नाही. पाठवल्यावर अहवाल येथे दिसेल.",loading:"मूल्यमापन सुरू आहे…",th_class:"वर्गीकरण",th_ev:"पुराव्याची पातळी",th_mean:"साध्या भाषेतील अर्थ",th_sim:"परिणाम उदाहरण (₹5,000/महिना × 12)",th_sig:"आढळलेले संकेत",disclaimer:"टीप: संगणक-निर्मित शैक्षणिक मूल्यमापन, गुंतवणूक सल्ला किंवा कायदेशीर निष्कर्ष नाही. कृतीपूर्वी SEBI / SCORES / NSE वर स्वतः तपासा.",learn_title:"गुंतवणूकदार शिक्षण",learn1:"NAV म्हणजे काय — म्युच्युअल फंडाच्या एका हिश्याची किंमत, रोज बदलते.",learn2:"SIP — दरमहा ठराविक सवय; चक्रवाढ संयमाचे फळ देते, टीपचे नाही.",learn3:"चढ-उतार — किंमत वर-खाली होते; हमखास नफा नसतोच.",learn4:"तक्रार — SCORES वर तक्रार करा; नामांकन व IEPF स्थिती पहा.",help_title:"हेल्पलाइन",news_title:"नवीन काय",news1:"फॉरवर्ड करण्यापूर्वी टीप-ग्रुप स्क्रीनशॉट तपासा.",news2:"डीमॅटसाठी नामांकन आता बंधनकारक.",news3:"IEPF मधून बेहक्क लाभांश परत मिळू शकतो.",links_title:"संबंधित दुवे",hist_title:"मागील मूल्यमापने",hist_empty:"या डिव्हाइसवर अद्याप नाही.",footer:"प्रात्यक्षिकासाठी मजकूर SANGYAN हॅकेथॉन टीमचा. स्रोत: SEBI · NSE · SCORES.",f_acc:"सुगमता",f_terms:"वापर अटी",f_priv:"गोपनीयता (PII नाही)",f_upd:"अद्यतन: ऑक्टो 2026"},
ta: {skip:"முக்கிய உள்ளடக்கத்திற்குச் செல்க",sra:"திரை வாசிப்பு அணுகல்",lang_more:"மேலும் மொழிகள்",nav_home:"முகப்பு",nav_check:"கோரிக்கையைச் சரிபார்",nav_report:"மதிப்பீட்டு அறிக்கை",nav_learn:"முதலீட்டாளர் கல்வி",nav_help:"உதவி எண்",ticker:"<strong>அறிவிப்பு:</strong> சந்தையில் உத்தரவாத வருமானம் யாரும் தர முடியாது. பணம் அனுப்பும் முன் SEBI / SCORES / NSE இல் பதிவைச் சரிபார்க்கவும். இந்த இணையதளம் கல்வி மட்டுமே தரும் — ஆலோசனை அல்ல.",crumb:"முகப்பு / முதலீட்டாளர் பாதுகாப்பு / கோரிக்கை மதிப்பீடு",h1:"ஆன்லைன் கோரிக்கை மதிப்பீட்டு வசதி",intro:"WhatsApp, Telegram, YouTube அல்லது Instagram இல் வந்த டிப், செய்தி அல்லது வீடியோ விளக்க உரையை ஒட்டவும். அது உங்களுக்குக் <strong>கற்பிக்கிறதா</strong> அல்லது <strong>விற்கிறதா</strong>, அதற்கு என்ன ஆதாரம் உள்ளது, எளிய பொருள் என்ன என்பதை இது கூறும்.",form_title:"விண்ணப்பம் — கோரிக்கை விவரம்",form_label:"கோரிக்கை / டிப் / விளக்க உரை",req:"(கட்டாயம்)",form_hint:"OTP, வங்கி கடவுச்சொல் அல்லது முழு கணக்கு எண்ணை எழுத வேண்டாம். கோரிக்கை உரை மட்டும் போதும்.",btn_check:"மதிப்பீட்டுக்கு அனுப்பு",btn_speak:"விளக்கத்தைக் கேள்",btn_clear:"படிவத்தை அழி",rep_title:"மதிப்பீட்டு அறிக்கை",empty:"இன்னும் மதிப்பீடு இல்லை. அனுப்பிய பிறகு அறிக்கை இங்கே தோன்றும்.",loading:"மதிப்பீடு நடக்கிறது…",th_class:"வகைப்பாடு",th_ev:"ஆதார நிலை",th_mean:"எளிய பொருள்",th_sim:"விளைவு எடுத்துக்காட்டு (₹5,000/மாதம் × 12)",th_sig:"கண்டறிந்த குறிகள்",disclaimer:"குறிப்பு: கணினி உருவாக்கிய கல்வி மதிப்பீடு; முதலீட்டு ஆலோசனை அல்லது சட்ட முடிவு அல்ல. செயல்படும் முன் SEBI / SCORES / NSE இல் சரிபார்க்கவும்.",learn_title:"முதலீட்டாளர் கல்வி",learn1:"NAV என்றால் என்ன — மியூச்சுவல் ஃபண்டின் ஒரு பங்கு மதிப்பு, தினமும் மாறும்.",learn2:"SIP — மாதந்தோறும் பழக்கம்; கூட்டு வளர்ச்சி பொறுமைக்குப் பலன் தரும், டிப்புக்கு அல்ல.",learn3:"ஏற்ற இறக்கம் — விலை ஏறும் இறங்கும்; உத்தரவாத லாபம் கிடையாது.",learn4:"புகார் — SCORES இல் புகார் செய்யுங்கள்; நாமினி மற்றும் IEPF நிலையைப் பாருங்கள்.",help_title:"உதவி எண்",news_title:"புதியவை",news1:"பகிரும் முன் டிப்-குழு ஸ்கிரீன்ஷாட்டைச் சரிபார்க்கவும்.",news2:"டீமேட்டுக்கு நாமினி இப்போது கட்டாயம்.",news3:"IEPF மூலம் உரிமை கோரா ஈவுத்தொகையை மீட்கலாம்.",links_title:"தொடர்புடைய இணைப்புகள்",hist_title:"முந்தைய மதிப்பீடுகள்",hist_empty:"இந்தச் சாதனத்தில் இதுவரை இல்லை.",footer:"செயல்விளக்க உள்ளடக்கம் SANGYAN ஹேக்கத்தான் குழுவினது. ஆதாரம்: SEBI · NSE · SCORES.",f_acc:"அணுகல்",f_terms:"பயன்பாட்டு விதிகள்",f_priv:"தனியுரிமை (PII இல்லை)",f_upd:"புதுப்பிப்பு: அக் 2026"},
bn: {skip:"মূল বিষয়বস্তুতে যান",sra:"স্ক্রিন রিডার অ্যাক্সেস",lang_more:"আরও ভাষা",nav_home:"মূলপৃষ্ঠা",nav_check:"দাবি যাচাই",nav_report:"মূল্যায়ন প্রতিবেদন",nav_learn:"বিনিয়োগকারী শিক্ষা",nav_help:"হেল্পলাইন",ticker:"<strong>বিজ্ঞপ্তি:</strong> বাজারে পাকা মুনাফার গ্যারান্টি কেউ দিতে পারে না। টাকা পাঠানোর আগে SEBI / SCORES / NSE-তে নিবন্ধন যাচাই করুন। এই পোর্টাল শুধু শিক্ষা দেয় — পরামর্শ নয়।",crumb:"মূলপৃষ্ঠা / বিনিয়োগকারী সুরক্ষা / দাবি মূল্যায়ন",h1:"অনলাইন দাবি মূল্যায়ন সুবিধা",intro:"WhatsApp, Telegram, YouTube বা Instagram-এ পাওয়া যেকোনো টিপ, বার্তা বা ভিডিও ক্যাপশনের পাঠ পেস্ট করুন। বিষয়বস্তু আপনাকে <strong>শেখাচ্ছে</strong> না <strong>বিক্রি করছে</strong>, এর পেছনে কী প্রমাণ আছে এবং সহজ অর্থ কী — তা এই সুবিধা জানাবে।",form_title:"আবেদন ফর্ম — দাবির বিবরণ",form_label:"দাবি / টিপ / ক্যাপশনের পাঠ",req:"(আবশ্যক)",form_hint:"OTP, ব্যাংক পাসওয়ার্ড বা পুরো অ্যাকাউন্ট নম্বর লিখবেন না। শুধু দাবির পাঠ দরকার।",btn_check:"মূল্যায়নের জন্য পাঠান",btn_speak:"ব্যাখ্যা শুনুন",btn_clear:"ফর্ম মুছুন",rep_title:"মূল্যায়ন প্রতিবেদন",empty:"এখনও কোনো মূল্যায়ন হয়নি। পাঠানোর পর প্রতিবেদন এখানে দেখা যাবে।",loading:"মূল্যায়ন চলছে…",th_class:"শ্রেণিবিভাগ",th_ev:"প্রমাণের মাত্রা",th_mean:"সহজ ভাষায় অর্থ",th_sim:"ফলাফলের উদাহরণ (₹5,000/মাস × 12)",th_sig:"পাওয়া সংকেত",disclaimer:"দাবিত্যাগ: কম্পিউটার-তৈরি শিক্ষামূলক মূল্যায়ন, বিনিয়োগ পরামর্শ বা আইনি সিদ্ধান্ত নয়। ব্যবস্থা নেওয়ার আগে SEBI / SCORES / NSE-তে নিজে যাচাই করুন।",learn_title:"বিনিয়োগকারী শিক্ষা",learn1:"NAV কী — মিউচুয়াল ফান্ডের এক ইউনিটের দাম, রোজ বদলায়।",learn2:"SIP — প্রতি মাসে নির্দিষ্ট অভ্যাস; চক্রবৃদ্ধি ধৈর্যের ফল দেয়, টিপের নয়।",learn3:"ওঠানামা — দাম ওঠে-নামে; পাকা মুনাফা হয়ই না।",learn4:"অভিযোগ — SCORES-এ অভিযোগ করুন; নমিনি ও IEPF অবস্থা দেখুন।",help_title:"হেল্পলাইন",news_title:"নতুন কী",news1:"ফরোয়ার্ড করার আগে টিপ-গ্রুপের স্ক্রিনশট যাচাই করুন।",news2:"ডিম্যাটের জন্য নমিনি এখন বাধ্যতামূলক।",news3:"IEPF থেকে বেদাবি লভ্যাংশ ফেরত পাওয়া যায়।",links_title:"সম্পর্কিত লিংক",hist_title:"আগের মূল্যায়ন",hist_empty:"এই ডিভাইসে এখনও কিছু নেই।",footer:"প্রদর্শনের জন্য বিষয়বস্তু SANGYAN হ্যাকাথন দলের। উৎস: SEBI · NSE · SCORES।",f_acc:"অ্যাক্সেসযোগ্যতা",f_terms:"ব্যবহারের শর্ত",f_priv:"গোপনীয়তা (কোনো PII নয়)",f_upd:"হালনাগাদ: অক্টো 2026"},
te: {skip:"ప్రధాన విషయానికి వెళ్ళండి",sra:"స్క్రీన్ రీడర్ యాక్సెస్",lang_more:"మరిన్ని భాషలు",nav_home:"హోమ్",nav_check:"క్లెయిమ్ తనిఖీ",nav_report:"మదింపు నివేదిక",nav_learn:"పెట్టుబడిదారుల విద్య",nav_help:"హెల్ప్‌లైన్",ticker:"<strong>గమనిక:</strong> మార్కెట్లో ఖచ్చితమైన లాభానికి ఎవరూ గ్యారెంటీ ఇవ్వలేరు. డబ్బు పంపే ముందు SEBI / SCORES / NSE లో నమోదు ధృవీకరించండి. ఈ పోర్టల్ విద్య మాత్రమే ఇస్తుంది — సలహా కాదు.",crumb:"హోమ్ / పెట్టుబడిదారుల రక్షణ / క్లెయిమ్ మదింపు",h1:"ఆన్‌లైన్ క్లెయిమ్ మదింపు సౌకర్యం",intro:"WhatsApp, Telegram, YouTube లేదా Instagram లో వచ్చిన ఏదైనా టిప్, సందేశం లేదా వీడియో శీర్షిక పాఠాన్ని అతికించండి. ఆ కంటెంట్ మీకు <strong>నేర్పుతోందా</strong> లేక <strong>అమ్ముతోందా</strong>, దానికి ఏ ఆధారం ఉంది, సులభ అర్థం ఏమిటో ఈ సౌకర్యం తెలియజేస్తుంది.",form_title:"దరఖాస్తు ఫారం — క్లెయిమ్ వివరాలు",form_label:"క్లెయిమ్ / టిప్ / శీర్షిక పాఠం",req:"(తప్పనిసరి)",form_hint:"OTP, బ్యాంక్ పాస్‌వర్డ్ లేదా పూర్తి ఖాతా నంబర్ రాయవద్దు. క్లెయిమ్ పాఠం మాత్రమే కావాలి.",btn_check:"మదింపుకు పంపండి",btn_speak:"వివరణ వినండి",btn_clear:"ఫారం తుడవండి",rep_title:"మదింపు నివేదిక",empty:"ఇంకా మదింపు జరగలేదు. పంపిన తర్వాత నివేదిక ఇక్కడ కనిపిస్తుంది.",loading:"మదింపు జరుగుతోంది…",th_class:"వర్గీకరణ",th_ev:"ఆధార స్థాయి",th_mean:"సులభ భాషలో అర్థం",th_sim:"ఫలిత ఉదాహరణ (₹5,000/నెల × 12)",th_sig:"కనుగొన్న సంకేతాలు",disclaimer:"గమనిక: కంప్యూటర్ రూపొందించిన విద్యా మదింపు; పెట్టుబడి సలహా లేదా చట్టపరమైన నిర్ణయం కాదు. చర్యకు ముందు SEBI / SCORES / NSE లో స్వయంగా ధృవీకరించండి.",learn_title:"పెట్టుబడిదారుల విద్య",learn1:"NAV అంటే ఏమిటి — మ్యూచువల్ ఫండ్ ఒక యూనిట్ ధర, రోజూ మారుతుంది.",learn2:"SIP — ప్రతి నెలా క్రమ అలవాటు; చక్రవడ్డీ ఓర్పుకు ఫలమిస్తుంది, టిప్పుకు కాదు.",learn3:"ఒడిదుడుకులు — ధరలు పైకి కిందికి కదులుతాయి; ఖచ్చితమైన లాభాలు ఉండవు.",learn4:"ఫిర్యాదు — SCORES లో ఫిర్యాదు చేయండి; నామినీ, IEPF స్థితి చూడండి.",help_title:"హెల్ప్‌లైన్",news_title:"కొత్తవి",news1:"ఫార్వార్డ్ చేసే ముందు టిప్-గ్రూప్ స్క్రీన్‌షాట్ తనిఖీ చేయండి.",news2:"డీమ్యాట్‌కు నామినీ ఇప్పుడు తప్పనిసరి.",news3:"IEPF ద్వారా క్లెయిమ్ చేయని డివిడెండ్ పొందవచ్చు.",links_title:"సంబంధిత లింకులు",hist_title:"గత మదింపులు",hist_empty:"ఈ పరికరంలో ఇంకా ఏమీ లేదు.",footer:"ప్రదర్శన నిమిత్తం కంటెంట్ SANGYAN హ్యాకథాన్ బృందానిది. మూలం: SEBI · NSE · SCORES.",f_acc:"యాక్సెసిబిలిటీ",f_terms:"వాడుక నిబంధనలు",f_priv:"గోప్యత (PII లేదు)",f_upd:"నవీకరణ: అక్టో 2026"},
kn: {skip:"ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ಹೋಗಿ",sra:"ಸ್ಕ್ರೀನ್ ರೀಡರ್ ಪ್ರವೇಶ",lang_more:"ಇನ್ನಷ್ಟು ಭಾಷೆಗಳು",nav_home:"ಮುಖಪುಟ",nav_check:"ಹಕ್ಕು ಪರಿಶೀಲಿಸಿ",nav_report:"ಮೌಲ್ಯಮಾಪನ ವರದಿ",nav_learn:"ಹೂಡಿಕೆದಾರರ ಶಿಕ್ಷಣ",nav_help:"ಸಹಾಯವಾಣಿ",ticker:"<strong>ಸೂಚನೆ:</strong> ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಖಾತರಿ ಲಾಭವನ್ನು ಯಾರೂ ನೀಡಲಾರರು. ಹಣ ಕಳುಹಿಸುವ ಮೊದಲು SEBI / SCORES / NSE ನಲ್ಲಿ ನೋಂದಣಿ ಪರಿಶೀಲಿಸಿ. ಈ ಪೋರ್ಟಲ್ ಶಿಕ್ಷಣ ಮಾತ್ರ ನೀಡುತ್ತದೆ — ಸಲಹೆಯಲ್ಲ.",crumb:"ಮುಖಪುಟ / ಹೂಡಿಕೆದಾರರ ರಕ್ಷಣೆ / ಹಕ್ಕು ಮೌಲ್ಯಮಾಪನ",h1:"ಆನ್‌ಲೈನ್ ಹಕ್ಕು ಮೌಲ್ಯಮಾಪನ ಸೌಲಭ್ಯ",intro:"WhatsApp, Telegram, YouTube ಅಥವಾ Instagram ನಲ್ಲಿ ಬಂದ ಯಾವುದೇ ಟಿಪ್, ಸಂದೇಶ ಅಥವಾ ವೀಡಿಯೊ ಶೀರ್ಷಿಕೆಯ ಪಠ್ಯವನ್ನು ಅಂಟಿಸಿ. ಆ ವಿಷಯವು ನಿಮಗೆ <strong>ಕಲಿಸುತ್ತಿದೆಯೇ</strong> ಅಥವಾ <strong>ಮಾರಾಟ ಮಾಡುತ್ತಿದೆಯೇ</strong>, ಅದಕ್ಕೆ ಏನು ಸಾಕ್ಷ್ಯವಿದೆ ಮತ್ತು ಸರಳ ಅರ್ಥವೇನು ಎಂದು ಈ ಸೌಲಭ್ಯ ತಿಳಿಸುತ್ತದೆ.",form_title:"ಅರ್ಜಿ ನಮೂನೆ — ಹಕ್ಕಿನ ವಿವರ",form_label:"ಹಕ್ಕು / ಟಿಪ್ / ಶೀರ್ಷಿಕೆಯ ಪಠ್ಯ",req:"(ಕಡ್ಡಾಯ)",form_hint:"OTP, ಬ್ಯಾಂಕ್ ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ ಪೂರ್ಣ ಖಾತೆ ಸಂಖ್ಯೆ ಬರೆಯಬೇಡಿ. ಹಕ್ಕಿನ ಪಠ್ಯ ಮಾತ್ರ ಬೇಕು.",btn_check:"ಮೌಲ್ಯಮಾಪನಕ್ಕೆ ಕಳುಹಿಸಿ",btn_speak:"ವಿವರಣೆ ಕೇಳಿ",btn_clear:"ನಮೂನೆ ಅಳಿಸಿ",rep_title:"ಮೌಲ್ಯಮಾಪನ ವರದಿ",empty:"ಇನ್ನೂ ಯಾವುದೇ ಮೌಲ್ಯಮಾಪನವಾಗಿಲ್ಲ. ಕಳುಹಿಸಿದ ನಂತರ ವರದಿ ಇಲ್ಲಿ ಕಾಣುತ್ತದೆ.",loading:"ಮೌಲ್ಯಮಾಪನ ನಡೆಯುತ್ತಿದೆ…",th_class:"ವರ್ಗೀಕರಣ",th_ev:"ಸಾಕ್ಷ್ಯ ಮಟ್ಟ",th_mean:"ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಅರ್ಥ",th_sim:"ಪರಿಣಾಮ ಉದಾಹರಣೆ (₹5,000/ತಿಂಗಳು × 12)",th_sig:"ಪತ್ತೆಯಾದ ಸೂಚನೆಗಳು",disclaimer:"ಹಕ್ಕುತ್ಯಾಗ: ಕಂಪ್ಯೂಟರ್ ನಿರ್ಮಿತ ಶೈಕ್ಷಣಿಕ ಮೌಲ್ಯಮಾಪನ, ಹೂಡಿಕೆ ಸಲಹೆ ಅಥವಾ ಕಾನೂನು ತೀರ್ಪಲ್ಲ. ಕ್ರಮಕ್ಕೂ ಮುನ್ನ SEBI / SCORES / NSE ನಲ್ಲಿ ನೀವೇ ಪರಿಶೀಲಿಸಿ.",learn_title:"ಹೂಡಿಕೆದಾರರ ಶಿಕ್ಷಣ",learn1:"NAV ಎಂದರೇನು — ಮ್ಯೂಚ್ಯುವಲ್ ಫಂಡ್‌ನ ಒಂದು ಯೂನಿಟ್ ಬೆಲೆ, ಪ್ರತಿದಿನ ಬದಲಾಗುತ್ತದೆ.",learn2:"SIP — ಪ್ರತಿ ತಿಂಗಳ ನಿಯತ ಅಭ್ಯಾಸ; ಚಕ್ರಬಡ್ಡಿ ತಾಳ್ಮೆಗೆ ಫಲ ನೀಡುತ್ತದೆ, ಟಿಪ್‌ಗಲ್ಲ.",learn3:"ಏರಿಳಿತ — ಬೆಲೆ ಮೇಲೆ-ಕೆಳಗೆ ಚಲಿಸುತ್ತದೆ; ಖಾತರಿ ಲಾಭವಿರುವುದಿಲ್ಲ.",learn4:"ದೂರು — SCORES ನಲ್ಲಿ ದೂರು ನೀಡಿ; ನಾಮಿನಿ ಮತ್ತು IEPF ಸ್ಥಿತಿ ನೋಡಿ.",help_title:"ಸಹಾಯವಾಣಿ",news_title:"ಹೊಸತೇನು",news1:"ಫಾರ್ವರ್ಡ್ ಮಾಡುವ ಮೊದಲು ಟಿಪ್-ಗ್ರೂಪ್ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಪರಿಶೀಲಿಸಿ.",news2:"ಡೀಮ್ಯಾಟ್‌ಗೆ ನಾಮಿನಿ ಈಗ ಕಡ್ಡಾಯ.",news3:"IEPF ಮೂಲಕ ಹಕ್ಕು ಸಲ್ಲಿಸದ ಲಾಭಾಂಶ ಪಡೆಯಬಹುದು.",links_title:"ಸಂಬಂಧಿತ ಕೊಂಡಿಗಳು",hist_title:"ಹಿಂದಿನ ಮೌಲ್ಯಮಾಪನಗಳು",hist_empty:"ಈ ಸಾಧನದಲ್ಲಿ ಇನ್ನೂ ಏನೂ ಇಲ್ಲ.",footer:"ಪ್ರಾತ್ಯಕ್ಷಿಕೆಗಾಗಿ ವಿಷಯ SANGYAN ಹ್ಯಾಕಥಾನ್ ತಂಡದ್ದು. ಮೂಲ: SEBI · NSE · SCORES.",f_acc:"ಪ್ರವೇಶಶೀಲತೆ",f_terms:"ಬಳಕೆ ನಿಯಮಗಳು",f_priv:"ಗೌಪ್ಯತೆ (PII ಇಲ್ಲ)",f_upd:"ನವೀಕರಣ: ಅಕ್ಟೋ 2026"},
ml: {skip:"പ്രധാന ഉള്ളടക്കത്തിലേക്ക് പോകൂ",sra:"സ്ക്രീൻ റീഡർ ആക്സസ്",lang_more:"കൂടുതൽ ഭാഷകൾ",nav_home:"മുഖപേജ്",nav_check:"അവകാശവാദം പരിശോധിക്കൂ",nav_report:"വിലയിരുത്തൽ റിപ്പോർട്ട്",nav_learn:"നിക്ഷേപക വിദ്യാഭ്യാസം",nav_help:"ഹെൽപ്‌ലൈൻ",ticker:"<strong>അറിയിപ്പ്:</strong> വിപണിയിൽ ഉറപ്പുള്ള ലാഭം ആർക്കും നൽകാനാവില്ല. പണം അയയ്ക്കുന്നതിന് മുൻപ് SEBI / SCORES / NSE ൽ രജിസ്ട്രേഷൻ പരിശോധിക്കൂ. ഈ പോർട്ടൽ വിദ്യാഭ്യാസം മാത്രം നൽകുന്നു — ഉപദേശമല്ല.",crumb:"മുഖപേജ് / നിക്ഷേപക സംരക്ഷണം / അവകാശവാദ വിലയിരുത്തൽ",h1:"ഓൺലൈൻ അവകാശവാദ വിലയിരുത്തൽ സൗകര്യം",intro:"WhatsApp, Telegram, YouTube അല്ലെങ്കിൽ Instagram ൽ ലഭിച്ച ഏതെങ്കിലും ടിപ്പ്, സന്ദേശം അല്ലെങ്കിൽ വീഡിയോ തലക്കെട്ടിന്റെ പാഠം ഒട്ടിക്കൂ. അത് നിങ്ങളെ <strong>പഠിപ്പിക്കുകയാണോ</strong> അതോ <strong>വിൽക്കുകയാണോ</strong>, അതിന് എന്ത് തെളിവുണ്ട്, ലളിതമായ അർത്ഥം എന്ത് എന്ന് ഈ സൗകര്യം പറയും.",form_title:"അപേക്ഷാ ഫോം — അവകാശവാദ വിവരം",form_label:"അവകാശവാദ / ടിപ്പ് / തലക്കെട്ടിന്റെ പാഠം",req:"(നിർബന്ധം)",form_hint:"OTP, ബാങ്ക് പാസ്‌വേഡ് അല്ലെങ്കിൽ മുഴുവൻ അക്കൗണ്ട് നമ്പർ എഴുതരുത്. അവകാശവാദ പാഠം മാത്രം മതി.",btn_check:"വിലയിരുത്തലിന് അയയ്ക്കൂ",btn_speak:"വിശദീകരണം കേൾക്കൂ",btn_clear:"ഫോം മായ്ക്കൂ",rep_title:"വിലയിരുത്തൽ റിപ്പോർട്ട്",empty:"ഇതുവരെ വിലയിരുത്തലില്ല. അയച്ച ശേഷം റിപ്പോർട്ട് ഇവിടെ കാണും.",loading:"വിലയിരുത്തൽ നടക്കുന്നു…",th_class:"തരംതിരിവ്",th_ev:"തെളിവിന്റെ നില",th_mean:"ലളിത ഭാഷയിൽ അർത്ഥം",th_sim:"ഫല ഉദാഹരണം (₹5,000/മാസം × 12)",th_sig:"കണ്ടെത്തിയ സൂചനകൾ",disclaimer:"അറിയിപ്പ്: കമ്പ്യൂട്ടർ നിർമ്മിത വിദ്യാഭ്യാസ വിലയിരുത്തൽ; നിക്ഷേപ ഉപദേശമോ നിയമപരമായ കണ്ടെത്തലോ അല്ല. പ്രവർത്തിക്കുന്നതിന് മുൻപ് SEBI / SCORES / NSE ൽ സ്വയം പരിശോധിക്കൂ.",learn_title:"നിക്ഷേപക വിദ്യാഭ്യാസം",learn1:"NAV എന്താണ് — മ്യൂച്വൽ ഫണ്ടിന്റെ ഒരു യൂണിറ്റിന്റെ വില, ദിവസവും മാറും.",learn2:"SIP — എല്ലാ മാസവും നിശ്ചിത ശീലം; കൂട്ടുപലിശ ക്ഷമയ്ക്ക് ഫലം നൽകും, ടിപ്പിനല്ല.",learn3:"ഏറ്റക്കുറച്ചിൽ — വില മുകളിലേക്കും താഴേക്കും മാറും; ഉറപ്പുള്ള ലാഭമില്ല.",learn4:"പരാതി — SCORES ൽ പരാതി നൽകൂ; നോമിനി, IEPF നില പരിശോധിക്കൂ.",help_title:"ഹെൽപ്‌ലൈൻ",news_title:"പുതിയവ",news1:"ഫോർവേഡ് ചെയ്യുന്നതിന് മുൻപ് ടിപ്പ്-ഗ്രൂപ്പ് സ്ക്രീൻഷോട്ട് പരിശോധിക്കൂ.",news2:"ഡീമാറ്റിന് നോമിനി ഇപ്പോൾ നിർബന്ധം.",news3:"IEPF വഴി അവകാശപ്പെടാത്ത ലভ്യാംശം തിരികെ നേടാം.",links_title:"ബന്ധപ്പെട്ട ലിങ്കുകൾ",hist_title:"മുൻ വിലയിരുത്തലുകൾ",hist_empty:"ഈ ഉപകരണത്തിൽ ഇതുവരെ ഒന്നുമില്ല.",footer:"പ്രദർശനത്തിനുള്ള ഉള്ളടക്കം SANGYAN ഹാക്കത്താൺ ടീമിന്റെത്. ഉറവിടം: SEBI · NSE · SCORES.",f_acc:"പ്രവേശനക്ഷമത",f_terms:"ഉപയോഗ നിബന്ധനകൾ",f_priv:"സ്വകാര്യത (PII ഇല്ല)",f_upd:"പുതുക്കം: ഒക്ടോ 2026"},
gu: {skip:"મુખ્ય સામગ્રી પર જાઓ",sra:"સ્ક્રીન રીડર એક્સેસ",lang_more:"વધુ ભાષાઓ",nav_home:"મુખ્યપૃષ્ઠ",nav_check:"દાવો તપાસો",nav_report:"મૂલ્યાંકન અહેવાલ",nav_learn:"રોકાણકાર શિક્ષણ",nav_help:"હેલ્પલાઇન",ticker:"<strong>સૂચના:</strong> બજારમાં પાકા નફાની ગેરંટી કોઈ આપી શકે નહીં. પૈસા મોકલતા પહેલા SEBI / SCORES / NSE પર નોંધણી ચકાસો. આ પોર્ટલ ફક્ત શિક્ષણ આપે છે — સલાહ નહીં.",crumb:"મુખ્યપૃષ્ઠ / રોકાણકાર સુરક્ષા / દાવા મૂલ્યાંકન",h1:"ઓનલાઇન દાવા મૂલ્યાંકન સુવિધા",intro:"WhatsApp, Telegram, YouTube કે Instagram પર મળેલી કોઈપણ ટિપ, સંદેશ કે વિડિયો કૅપ્શનનો પાઠ ચોંટાડો. તે તમને <strong>શીખવી</strong> રહ્યું છે કે <strong>વેચી</strong> રહ્યું છે, તેની પાછળ શું પુરાવો છે અને સરળ અર્થ શું છે તે આ સુવિધા જણાવશે.",form_title:"અરજી ફોર્મ — દાવાની વિગત",form_label:"દાવા / ટિપ / કૅપ્શનનો પાઠ",req:"(જરૂરી)",form_hint:"OTP, બેંક પાસવર્ડ કે પૂરો ખાતા નંબર ન લખો. ફક્ત દાવાનો પાઠ જોઈએ.",btn_check:"મૂલ્યાંકન માટે મોકલો",btn_speak:"સમજૂતી સાંભળો",btn_clear:"ફોર્મ સાફ કરો",rep_title:"મૂલ્યાંકન અહેવાલ",empty:"હજુ કોઈ મૂલ્યાંકન થયું નથી. મોકલ્યા પછી અહેવાલ અહીં દેખાશે.",loading:"મૂલ્યાંકન ચાલી રહ્યું છે…",th_class:"વર્ગીકરણ",th_ev:"પુરાવાનું સ્તર",th_mean:"સરળ ભાષામાં અર્થ",th_sim:"પરિણામ ઉદાહરણ (₹5,000/મહિને × 12)",th_sig:"મળેલા સંકેતો",disclaimer:"નોંધ: કમ્પ્યુટર-નિર્મિત શૈક્ષણિક મૂલ્યાંકન, રોકાણ સલાહ કે કાનૂની તારણ નહીં. કાર્યવાહી પહેલા SEBI / SCORES / NSE પર જાતે ચકાસો.",learn_title:"રોકાણકાર શિક્ષણ",learn1:"NAV શું છે — મ્યુચ્યુઅલ ફંડના એક યુનિટની કિંમત, રોજ બદલાય છે.",learn2:"SIP — દર મહિને નિશ્ચિત ટેવ; ચક્રવૃદ્ધિ ધીરજનું ફળ આપે છે, ટિપનું નહીં.",learn3:"વધઘટ — કિંમત ઉપર-નીચે થાય છે; પાકો નફો હોતો જ નથી.",learn4:"ફરિયાદ — SCORES પર ફરિયાદ કરો; નોમિની અને IEPF સ્થિતિ જુઓ.",help_title:"હેલ્પલાઇન",news_title:"નવું શું",news1:"ફોરવર્ડ કરતા પહેલા ટિપ-ગ્રુપ સ્ક્રીનશોટ તપાસો.",news2:"ડીમેટ માટે નોમિની હવે ફરજિયાત.",news3:"IEPF દ્વારા બેદાવા ડિવિડન્ડ પાછું મેળવી શકાય.",links_title:"સંબંધિત લિંક",hist_title:"અગાઉના મૂલ્યાંકન",hist_empty:"આ ડિવાઇસ પર હજુ કંઈ નથી.",footer:"પ્રદર્શન માટે સામગ્રી SANGYAN હેકાથોન ટીમની. સ્રોત: SEBI · NSE · SCORES.",f_acc:"સુગમતા",f_terms:"વપરાશ શરતો",f_priv:"ગોપનીયતા (PII નહીં)",f_upd:"અપડેટ: ઓક્ટો 2026"},
pa: {skip:"ਮੁੱਖ ਸਮੱਗਰੀ ’ਤੇ ਜਾਓ",sra:"ਸਕ੍ਰੀਨ ਰੀਡਰ ਪਹੁੰਚ",lang_more:"ਹੋਰ ਭਾਸ਼ਾਵਾਂ",nav_home:"ਮੁੱਖ ਪੰਨਾ",nav_check:"ਦਾਅਵਾ ਜਾਂਚੋ",nav_report:"ਮੁਲਾਂਕਣ ਰਿਪੋਰਟ",nav_learn:"ਨਿਵੇਸ਼ਕ ਸਿੱਖਿਆ",nav_help:"ਹੈਲਪਲਾਈਨ",ticker:"<strong>ਸੂਚਨਾ:</strong> ਬਾਜ਼ਾਰ ਵਿੱਚ ਪੱਕੇ ਮੁਨਾਫ਼ੇ ਦੀ ਗਾਰੰਟੀ ਕੋਈ ਨਹੀਂ ਦੇ ਸਕਦਾ। ਪੈਸੇ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ SEBI / SCORES / NSE ’ਤੇ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ। ਇਹ ਪੋਰਟਲ ਸਿਰਫ਼ ਸਿੱਖਿਆ ਦਿੰਦਾ ਹੈ — ਸਲਾਹ ਨਹੀਂ।",crumb:"ਮੁੱਖ ਪੰਨਾ / ਨਿਵੇਸ਼ਕ ਸੁਰੱਖਿਆ / ਦਾਅਵਾ ਮੁਲਾਂਕਣ",h1:"ਔਨਲਾਈਨ ਦਾਅਵਾ ਮੁਲਾਂਕਣ ਸਹੂਲਤ",intro:"WhatsApp, Telegram, YouTube ਜਾਂ Instagram ’ਤੇ ਮਿਲੀ ਕਿਸੇ ਵੀ ਟਿਪ, ਸੁਨੇਹੇ ਜਾਂ ਵੀਡੀਓ ਕੈਪਸ਼ਨ ਦਾ ਪਾਠ ਚਿਪਕਾਓ। ਇਹ ਸਹੂਲਤ ਦੱਸੇਗੀ ਕਿ ਸਮੱਗਰੀ ਤੁਹਾਨੂੰ <strong>ਸਿਖਾ</strong> ਰਹੀ ਹੈ ਜਾਂ <strong>ਵੇਚ</strong> ਰਹੀ ਹੈ, ਇਸ ਪਿੱਛੇ ਕੀ ਸਬੂਤ ਹੈ ਅਤੇ ਸਿੱਧਾ ਅਰਥ ਕੀ ਹੈ।",form_title:"ਅਰਜ਼ੀ ਫਾਰਮ — ਦਾਅਵੇ ਦਾ ਵੇਰਵਾ",form_label:"ਦਾਅਵੇ / ਟਿਪ / ਕੈਪਸ਼ਨ ਦਾ ਪਾਠ",req:"(ਲਾਜ਼ਮੀ)",form_hint:"OTP, ਬੈਂਕ ਪਾਸਵਰਡ ਜਾਂ ਪੂਰਾ ਖਾਤਾ ਨੰਬਰ ਨਾ ਲਿਖੋ। ਸਿਰਫ਼ ਦਾਅਵੇ ਦਾ ਪਾਠ ਚਾਹੀਦਾ ਹੈ।",btn_check:"ਮੁਲਾਂਕਣ ਲਈ ਭੇਜੋ",btn_speak:"ਵਿਆਖਿਆ ਸੁਣੋ",btn_clear:"ਫਾਰਮ ਸਾਫ਼ ਕਰੋ",rep_title:"ਮੁਲਾਂਕਣ ਰਿਪੋਰਟ",empty:"ਅਜੇ ਕੋਈ ਮੁਲਾਂਕਣ ਨਹੀਂ ਹੋਇਆ। ਭੇਜਣ ਤੋਂ ਬਾਅਦ ਰਿਪੋਰਟ ਇੱਥੇ ਦਿਖੇਗੀ।",loading:"ਮੁਲਾਂਕਣ ਚੱਲ ਰਿਹਾ ਹੈ…",th_class:"ਵਰਗੀਕਰਨ",th_ev:"ਸਬੂਤ ਦਾ ਪੱਧਰ",th_mean:"ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ ਅਰਥ",th_sim:"ਨਤੀਜਾ ਉਦਾਹਰਨ (₹5,000/ਮਹੀਨਾ × 12)",th_sig:"ਮਿਲੇ ਸੰਕੇਤ",disclaimer:"ਨੋਟ: ਕੰਪਿਊਟਰ-ਨਿਰਮਿਤ ਵਿਦਿਅਕ ਮੁਲਾਂਕਣ, ਨਿਵੇਸ਼ ਸਲਾਹ ਜਾਂ ਕਾਨੂੰਨੀ ਸਿੱਟਾ ਨਹੀਂ। ਕਾਰਵਾਈ ਤੋਂ ਪਹਿਲਾਂ SEBI / SCORES / NSE ’ਤੇ ਖ਼ੁਦ ਪੁਸ਼ਟੀ ਕਰੋ।",learn_title:"ਨਿਵੇਸ਼ਕ ਸਿੱਖਿਆ",learn1:"NAV ਕੀ ਹੈ — ਮਿਊਚੁਅਲ ਫੰਡ ਦੇ ਇੱਕ ਯੂਨਿਟ ਦੀ ਕੀਮਤ, ਰੋਜ਼ ਬਦਲਦੀ ਹੈ।",learn2:"SIP — ਹਰ ਮਹੀਨੇ ਨਿਸ਼ਚਿਤ ਆਦਤ; ਚੱਕਰਵਾਧ ਧੀਰਜ ਦਾ ਫਲ ਦਿੰਦਾ ਹੈ, ਟਿਪ ਦਾ ਨਹੀਂ।",learn3:"ਉਤਰਾਅ-ਚੜ੍ਹਾਅ — ਕੀਮਤ ਉੱਪਰ-ਹੇਠਾਂ ਹੁੰਦੀ ਹੈ; ਪੱਕਾ ਮੁਨਾਫ਼ਾ ਹੁੰਦਾ ਹੀ ਨਹੀਂ।",learn4:"ਸ਼ਿਕਾਇਤ — SCORES ’ਤੇ ਸ਼ਿਕਾਇਤ ਕਰੋ; ਨਾਮਜ਼ਦਗੀ ਅਤੇ IEPF ਸਥਿਤੀ ਵੇਖੋ।",help_title:"ਹੈਲਪਲਾਈਨ",news_title:"ਨਵਾਂ ਕੀ",news1:"ਫਾਰਵਰਡ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਟਿਪ-ਗਰੁੱਪ ਸਕ੍ਰੀਨਸ਼ਾਟ ਜਾਂਚੋ।",news2:"ਡੀਮੈਟ ਲਈ ਨਾਮਜ਼ਦਗੀ ਹੁਣ ਲਾਜ਼ਮੀ।",news3:"IEPF ਰਾਹੀਂ ਬੇਦਾਅਵਾ ਲਾਭਅੰਸ਼ ਵਾਪਸ ਮਿਲ ਸਕਦਾ ਹੈ।",links_title:"ਸਬੰਧਿਤ ਲਿੰਕ",hist_title:"ਪਿਛਲੇ ਮੁਲਾਂਕਣ",hist_empty:"ਇਸ ਡਿਵਾਈਸ ’ਤੇ ਅਜੇ ਕੁਝ ਨਹੀਂ।",footer:"ਪ੍ਰਦਰਸ਼ਨ ਲਈ ਸਮੱਗਰੀ SANGYAN ਹੈਕਾਥਨ ਟੀਮ ਦੀ। ਸਰੋਤ: SEBI · NSE · SCORES.",f_acc:"ਪਹੁੰਚਯੋਗਤਾ",f_terms:"ਵਰਤੋਂ ਸ਼ਰਤਾਂ",f_priv:"ਗੋਪਨੀਯਤਾ (ਕੋਈ PII ਨਹੀਂ)",f_upd:"ਅਪਡੇਟ: ਅਕਤੂ 2026"}}

const HTML_LANG = {en: "en", hinglish: "hi", hi: "hi", mr: "mr", ta: "ta", bn: "bn", te: "te", kn: "kn", ml: "ml", gu: "gu", pa: "pa"};
const SPEECH_LANG = {hi: "hi-IN", mr: "mr-IN", ta: "ta-IN", bn: "bn-IN", te: "te-IN", kn: "kn-IN", ml: "ml-IN", gu: "gu-IN", pa: "pa-IN"};

function applyLang() {
  const d = I18N[LANG] || I18N.en;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const v = d[el.dataset.i18n];
    if (v !== undefined) el.innerHTML = v;
  });
  document.documentElement.lang = HTML_LANG[LANG] || "en";
  document.querySelectorAll(".langs button").forEach((x) =>
    x.setAttribute("aria-pressed", String(x.dataset.lang === LANG)));
}

document.querySelectorAll(".langs button").forEach((b) =>
  b.addEventListener("click", () => {
    if (LANG === b.dataset.lang) return;
    LANG = b.dataset.lang;
    $("lang-more").value = "";
    applyLang();
    if (LAST && !$("out").hidden) doCheck(); // re-assess in the new language
  })
);

$("lang-more").addEventListener("change", (e) => {
  if (!e.target.value) return;
  LANG = e.target.value;
  applyLang();
  if (LAST && !$("out").hidden) doCheck();
});

async function doCheck() {
  const text = $("claim").value.trim();
  $("form-err").hidden = true;
  if (!text) { const e = $("form-err"); e.textContent = "Paste some text first — a tip, message, or caption."; e.hidden = false; return; }
  $("empty").hidden = true; $("out").hidden = true; $("loading").hidden = false; $("speak").disabled = true;
  try {
    const r = await fetch(`${API}/api/analyze`, {
      method: "POST", headers: {"Content-Type": "application/json"},
      body: JSON.stringify({input_text: text, lang: LANG}),
    });
    if (!r.ok) throw new Error(`Server said ${r.status}`);
    LAST = await r.json();
    render(LAST); saveHist(LAST);
  } catch (err) {
    const e = $("form-err"); e.textContent = `Could not check. Is the backend on :8001? (${err.message})`; e.hidden = false;
    $("empty").hidden = false;
  } finally { $("loading").hidden = true; }
}

$("check").addEventListener("click", doCheck);

function render(d) {
  $("out").hidden = false; $("speak").disabled = false;
  const p = $("promo"); p.textContent = d.promo_label;
  p.className = "badge " + (d.promo_label === "education" ? "b-edu" : d.promo_label === "mixed" ? "b-mixed" : "b-promo");
  $("score").textContent = `score ${d.promo_score}`;
  document.querySelectorAll(".meter span").forEach((s, i) => {
    s.className = i === 0 ? "on-" + d.evidence.level : "";
  });
  $("ev").textContent = d.evidence.summary;
  $("ev-u").textContent = "Uncertainty: " + d.evidence.uncertainty;
  $("src").innerHTML = (d.evidence.sources || []).map((s) => `<li><a href="${s.url}" target="_blank" rel="noopener">${s.title}</a></li>`).join("");
  $("plain").textContent = d.explainer.plain_text;
  $("analogy").textContent = d.explainer.analogy;
  $("terms").innerHTML = (d.explainer.terms || []).map((t) => `<li><strong>${t.term}:</strong> ${t.meaning}</li>`).join("");
  $("sig").innerHTML = (d.promo_signals || []).map((s) => `<li>${s}</li>`).join("") || "<li>None</li>";
  drawChart(d.simulator);
  $("sim-note").textContent = d.simulator.inputs.note || "";
}

function drawChart(sim) {
  const cv = $("chart"), ctx = cv.getContext("2d");
  ctx.clearRect(0, 0, cv.width, cv.height);
  const real = sim.projection, hype = sim.inputs.hype_series || null;
  const max = Math.max(...real, ...(hype || [0])) || 1;
  const X = (i, n) => 30 + (i / Math.max(1, n - 1)) * (cv.width - 50);
  const Y = (v) => cv.height - 20 - (v / max) * (cv.height - 50);
  ctx.strokeStyle = "#D5D5D5"; ctx.beginPath(); ctx.moveTo(30, 10); ctx.lineTo(30, cv.height - 20); ctx.lineTo(cv.width - 10, cv.height - 20); ctx.stroke();
  const line = (arr, col, dash) => { ctx.strokeStyle = col; ctx.lineWidth = 2; ctx.setLineDash(dash || []); ctx.beginPath(); arr.forEach((v, i) => i ? ctx.lineTo(X(i, arr.length), Y(v)) : ctx.moveTo(X(0, arr.length), Y(v))); ctx.stroke(); ctx.setLineDash([]); };
  line(real, "#0B3C5D");
  if (hype) line(hype, "#C62828", [6, 4]);
  ctx.fillStyle = "#5A5A5A"; ctx.font = "12px sans-serif";
  ctx.fillText("steady", 34, 22); if (hype) { ctx.fillStyle = "#C62828"; ctx.fillText("hype claim", 90, 22); }
}

$("speak").addEventListener("click", () => {
  if (!LAST) return;
  const u = new SpeechSynthesisUtterance(LAST.explainer.plain_text + " " + LAST.explainer.analogy);
  u.lang = SPEECH_LANG[LANG] || "en-IN";
  speechSynthesis.cancel(); speechSynthesis.speak(u);
});

function saveHist(d) {
  const k = "sangyan-hist", arr = JSON.parse(localStorage.getItem(k) || "[]");
  arr.unshift({t: new Date().toLocaleString(), label: d.promo_label, ev: d.evidence.level, txt: d.claims[0]?.text?.slice(0, 80)});
  localStorage.setItem(k, JSON.stringify(arr.slice(0, 8)));
  $("hist").innerHTML = arr.slice(0, 8).map((h) => `<div>${h.t} — <strong>${h.label}</strong> / evidence ${h.ev} — ${h.txt}</div>`).join("");
}

$("clear").addEventListener("click", () => {
  $("claim").value = ""; $("out").hidden = true; $("empty").hidden = false;
  $("form-err").hidden = true; LAST = null; $("speak").disabled = true;
});

let FS = 16;
const setFS = (v) => { FS = Math.min(20, Math.max(13, v)); document.documentElement.style.setProperty("--fs", FS + "px"); };
$("f-inc").addEventListener("click", () => setFS(FS + 1));
$("f-dec").addEventListener("click", () => setFS(FS - 1));
$("f-reset").addEventListener("click", () => setFS(16));

applyLang();
