"""Sync the official corpus: SEBI Financial Education Booklet (PDF) + SEBI
investor pages -> app/kb_official.py chunks with source links. Re-runnable.
Usage: python3 kb_sync.py  (run from backend/)"""
import os
import re
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
BOOKLET_URL = "https://investor.sebi.gov.in/pdf/downloadable-documents/Financial%20Education%20Booklet%20-%20English.pdf"
PAGES = [
    ("https://investor.sebi.gov.in/understanding_mf.html", "sebi-mf", "SEBI explains mutual funds"),
]

os.makedirs(DATA, exist_ok=True)


def get(url: str, dest: str) -> bool:
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 Saarthi/1.0"})
        with urllib.request.urlopen(req, timeout=60) as r, open(dest, "wb") as f:
            f.write(r.read(50 * 1024 * 1024))
        return True
    except Exception as e:
        print("fetch failed:", url, str(e)[:100])
        return False


def pdf_text(path: str) -> str:
    out = path + ".txt"
    subprocess.run(["pdftotext", "-layout", path, out], check=True, timeout=120)
    with open(out, encoding="utf-8", errors="ignore") as f:
        return f.read()


def chunks_of(title: str, text: str, source: str, prefix: str, size: int = 900) -> list[dict]:
    text = re.sub(r"\s+", " ", text).strip()
    docs, i = [], 0
    while i < len(text):
        cut = text[i:i + size]
        docs.append({"id": f"{prefix}-{len(docs)}", "title": title,
                     "body": cut, "links": [source]})
        i += size
    return docs


def split_chapters(text: str) -> list[tuple[str, str]]:
    parts = re.split(r"(Chapter\s+\d+\s*[-–:–.]?\s*[^\n]{0,80})", text)
    out = []
    for i in range(1, len(parts), 2):
        head = parts[i].strip()
        body = parts[i + 1] if i + 1 < len(parts) else ""
        if len(body.strip()) > 300:
            out.append((head, body))
    return out


def main() -> None:
    docs: list[dict] = []
    pdf = os.path.join(DATA, "sebi-booklet.pdf")
    if get(BOOKLET_URL, pdf):
        try:
            text = pdf_text(pdf)
            chaps = split_chapters(text)
            print(f"booklet: {len(text)} chars, {len(chaps)} chapters")
            for head, body in chaps:
                docs += chunks_of("SEBI booklet: " + head, body, BOOKLET_URL, "sebi-book")
        except Exception as e:
            print("pdf parse failed:", str(e)[:120])
    sys.path.insert(0, os.path.join(HERE, "app"))
    from ingest import extract_article_text
    for url, pid, title in PAGES:
        text, note = extract_article_text(url, limit=12000)
        if text and len(text) > 500:
            docs += chunks_of(title, text, url, pid)
            print(f"page ok: {pid} ({len(text)} chars)")
        else:
            print(f"page skipped: {pid} ({note})")
    with open(os.path.join(HERE, "app", "kb_official.py"), "w", encoding="utf-8") as f:
        f.write('"""Official corpus (SEBI). Auto-generated by kb_sync.py — do not hand-edit."""\n\nDOCS = [\n')
        for d in docs:
            body = d["body"].replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'{{"id": "{d["id"]}", "title": "{d["title"]}", "body": "{body}", "links": {d["links"]}}},\n')
        f.write("]\n")
    print(f"wrote {len(docs)} official chunks")


if __name__ == "__main__":
    main()
