"""Curated investor-education knowledge base (EN + HI). Each doc: what it is,
why it matters, what to watch out for, plus official links. This is the RAG
corpus for /api/search — no scraping, works fully offline."""

DOCS = [
{"id": "nav", "links": ["https://www.amfiindia.com"],
 "title_en": "NAV — Net Asset Value", "title_hi": "NAV — शुद्ध परिसंपत्ति मूल्य",
 "body_en": "NAV is the per-unit price of a mutual fund, declared daily after market close. You buy and sell units at the applicable NAV, not at yesterday's price. A low NAV does NOT mean a fund is cheap — ₹10 NAV and ₹100 NAV funds can hold the same stocks. Watch out: anyone selling a fund 'because its NAV is low' is misleading you.",
 "body_hi": "NAV म्यूचुअल फंड की एक यूनिट की कीमत है, जो बाज़ार बंद होने के बाद रोज़ घोषित होती है। आप उसी दिन के NAV पर यूनिट खरीदते-बेचते हैं। कम NAV का मतलब सस्ता फंड नहीं — ₹10 और ₹100 NAV वाले फंड में एक जैसे शेयर हो सकते हैं। सावधान: 'NAV कम है इसलिए लो' कहने वाला गुमराह कर रहा है।"},
{"id": "sip", "links": ["https://www.amfiindia.com"],
 "title_en": "SIP — Systematic Investment Plan", "title_hi": "SIP — व्यवस्थित निवेश योजना",
 "body_en": "A SIP invests a fixed amount every month into a mutual fund. It builds discipline and averages your purchase cost across ups and downs (rupee-cost averaging). Stopping a SIP in a crash locks in the worst outcome — the recovery is where compounding works hardest. Watch out: 'guaranteed SIP returns' is a lie; no market return is guaranteed.",
 "body_hi": "SIP हर महीने तय राशि म्यूचुअल फंड में लगाती है। इससे अनुशासन बनता है और उतार-चढ़ाव में औसत खरीद-लागत मिलती है। गिरावट में SIP रोकना सबसे बुरा फैसला है — भरपाई के समय ही चक्रवृद्धि सबसे ज़्यादा काम करती है। सावधान: 'गारंटीड SIP रिटर्न' झूठ है।"},
{"id": "compounding", "links": ["https://www.sebi.gov.in"],
 "title_en": "Compounding — profit on profit", "title_hi": "चक्रवृद्धि — मुनाफे पर मुनाफा",
 "body_en": "Compounding means your profits start earning their own profits. Its power comes from TIME, not high returns: money left alone for 15 years beats clever short-term bets. Starting 5 years early matters more than finding 2% extra return. Watch out: schemes promising 'fast compounding' or 'daily compounding profits' are usually ponzi traps.",
 "body_hi": "चक्रवृद्धि में मुनाफा खुद मुनाफा कमाने लगता है। इसकी ताक़त समय से आती है, ज़्यादा रिटर्न से नहीं: 15 साल छुआ न गया पैसा चालाक छोटे दांवों को हरा देता है। 5 साल जल्दी शुरू करना, 2% ज़्यादा रिटर्न ढूंढने से बड़ा है। सावधान: 'तेज़ चक्रवृद्धि' का वादा करने वाली योजनाएं अक्सर पोंजी जाल होती हैं।"},
{"id": "volatility", "links": ["https://www.nseindia.com"],
 "title_en": "Volatility — prices move up and down", "title_hi": "उतार-चढ़ाव — कीमत ऊपर-नीचे होती है",
 "body_en": "Volatility is how sharply prices swing. Equity markets falling 10-20% in a bad year is NORMAL, not a signal that investing is broken. Panic-selling during dips converts temporary falls into permanent losses. Watch out: anyone who shows you only rising charts is hiding half the truth.",
 "body_hi": "उतार-चढ़ाव कीमतों के तेज़ हिलने को कहते हैं। बुरे साल में 10-20% गिरना सामान्य है — यह निवेश टूटने का संकेत नहीं। गिरावट में घबराकर बेचना अस्थायी नुकसान को स्थायी बना देता है। सावधान: जो सिर्फ़ चढ़ते चार्ट दिखाए, वह आधा सच छिपा रहा है।"},
{"id": "diversification", "links": ["https://www.sebi.gov.in"],
 "title_en": "Diversification — don't put everything in one place", "title_hi": "विविधीकरण — सब कुछ एक जगह न रखें",
 "body_en": "Diversification spreads money across different assets so one failure cannot wipe you out. A single 'hot tip' stock going to zero should never decide your family's future. Watch out: putting your full savings into one Telegram tip is the opposite of diversification — it is gambling.",
 "body_hi": "विविधीकरण पैसा अलग-अलग जगह बांटता है ताकि एक असफलता सब कुछ न मिटाए। एक 'हॉट टिप' शेयर का शून्य होना आपके परिवार का भविष्य तय न करे। सावधान: पूरी बचत एक टेलीग्राम टिप में लगाना विविधीकरण का उल्टा है — यह जुआ है।"},
{"id": "demat", "links": ["https://nsdl.co.in", "https://www.cdslindia.com"],
 "title_en": "Demat account — digital locker for shares", "title_hi": "डीमैट खाता — शेयरों का डिजिटल लॉकर",
 "body_en": "A demat account holds your shares digitally with NSDL or CDSL. Opening one needs KYC and takes a few days; no real broker pressures you to 'open in 5 minutes'. Never share your demat login, OTP, or POA blindly — with access, anyone can sell your holdings. Watch out: fake broker apps that look real but steal logins.",
 "body_hi": "डीमैट खाता NSDL या CDSL के पास आपके शेयर डिजिटल रूप में रखता है। इसे खोलने में KYC लगती है और कुछ दिन लगते हैं; कोई असली ब्रोकर '5 मिनट में खोलो' का दबाव नहीं डालता। लॉगिन, OTP या POA कभी साझा न करें — पहुंच मिलने पर कोई भी आपकी होल्डिंग बेच सकता है। सावधान: असली दिखने वाले नकली ब्रोकर ऐप।"},
{"id": "nomination", "links": ["https://www.sebi.gov.in"],
 "title_en": "Nomination — who gets your money after you", "title_hi": "नामांकन — आपके बाद पैसा किसे मिलेगा",
 "body_en": "Nomination names who receives your shares and mutual funds if something happens to you. Without it, your family faces long legal processes to claim their own money. SEBI has made nomination (or an opt-out declaration) mandatory for demat accounts. Watch out: check every folio — bank, demat, mutual funds — separately.",
 "body_hi": "नामांकन तय करता है कि आपके बाद शेयर व म्यूचुअल फंड किसे मिलेंगे। इसके बिना परिवार को अपना ही पैसा पाने में लंबी कानूनी प्रक्रिया झेलनी पड़ती है। SEBI ने डीमैट हेतु नामांकन (या छूट-घोषणा) अनिवार्य किया है। सावधान: हर फोलियो — बैंक, डीमैट, म्यूचुअल फंड — अलग से जांचें।"},
{"id": "scores", "links": ["https://scores.sebi.gov.in"],
 "title_en": "SCORES — free complaint portal", "title_hi": "SCORES — मुफ़्त शिकायत पोर्टल",
 "body_en": "SCORES (scores.sebi.gov.in) is SEBI's free portal to complain against brokers, companies, and mutual funds. Keep your complaint short, attach contract notes and screenshots, and note dates. Entities must respond within set timelines, and SEBI escalates ignored complaints. Watch out: nobody from 'SCORES' will ever call asking for money to release your refund.",
 "body_hi": "SCORES (scores.sebi.gov.in) ब्रोकर, कंपनी व म्यूचुअल फंड के ख़िलाफ़ SEBI का मुफ़्त शिकायत पोर्टल है। शिकायत छोटी रखें, कॉन्ट्रैक्ट नोट व स्क्रीनशॉट लगाएं, तारीखें लिखें। तय समय में जवाब देना होता है, अनदेखी पर SEBI कार्रवाई बढ़ाता है। सावधान: 'SCORES से' कहकर रिफंड हेतु पैसे मांगने वाली कॉल ठगी है।"},
{"id": "iepf", "links": ["https://www.iepf.gov.in"],
 "title_en": "IEPF — recover unclaimed dividends and shares", "title_hi": "IEPF — बेदावा लाभांश व शेयर वापस पाएं",
 "body_en": "Dividends and shares unclaimed for 7 years move to the IEPF fund — but they remain YOURS and can be claimed back free at iepf.gov.in. Legal heirs often don't know old shares exist; check family folios. Watch out: agents demanding big fees to 'release IEPF money' are unnecessary — the process is free and online.",
 "body_hi": "7 साल तक बेदावा लाभांश व शेयर IEPF फंड में जाते हैं — पर वे आपके ही रहते हैं और iepf.gov.in पर मुफ़्त वापस मिलते हैं। वारिसों को अक्सर पुराने शेयरों का पता नहीं होता; परिवार के फोलियो जांचें। सावधान: 'IEPF पैसा निकलवाने' हेतु मोटी फीस मांगने वाले एजेंट बेकार हैं — प्रक्रिया मुफ़्त व ऑनलाइन है।"},
{"id": "kyc", "links": ["https://www.sebi.gov.in"],
 "title_en": "KYC — know your customer", "title_hi": "KYC — अपने ग्राहक को जानें",
 "body_en": "KYC (PAN, Aadhaar, photo, address proof) is a one-time identity check required before investing. Do it only on official broker, fund, or KRA websites — never over WhatsApp links. Real KYC never asks for OTPs on calls. Watch out: 'KYC suspended, click to verify' messages are phishing to steal your identity.",
 "body_hi": "KYC (PAN, आधार, फोटो, पता-प्रमाण) निवेश से पहले एक बार की पहचान-जांच है। इसे सिर्फ़ आधिकारिक ब्रोकर, फंड या KRA वेबसाइट पर करें — WhatsApp लिंक पर कभी नहीं। असली KYC कॉल पर OTP नहीं मांगती। सावधान: 'KYC बंद, सत्यापित हेतु क्लिक करें' संदेश पहचान-चोरी (फिशिंग) हैं।"},
{"id": "ponzi", "links": ["https://www.sebi.gov.in", "https://www.rbi.org.in"],
 "title_en": "Ponzi schemes — how to spot them", "title_hi": "पोंजी योजनाएं — पहचान कैसे करें",
 "body_en": "Ponzi schemes pay old investors with new investors' money and collapse when newcomers stop. Red flags: fixed high monthly returns, joining bonuses, pressure to recruit family, no SEBI/RBI registration, secretive 'trading strategies'. Real profits fluctuate; only scams promise smooth fixed income from markets. If it sounds too good, verify registration first — or walk away.",
 "body_hi": "पोंजी योजनाएं नए निवेशकों के पैसे से पुरानों को देती हैं और नए लोग रुकते ही ढह जाती हैं। लाल झंडे: तय मासिक ऊंचा रिटर्न, जुड़ने पर बोनस, परिवार जोड़ने का दबाव, SEBI/RBI पंजीकरण नहीं, गुप्त 'ट्रेडिंग रणनीति'। असली मुनाफा घटता-बढ़ता है; बाज़ार से तय आय का वादा सिर्फ़ ठगी करती है। अच्छा लगे तो पहले पंजीकरण जांचें — या दूर रहें।"},
{"id": "upi_fraud", "links": ["https://www.rbi.org.in"],
 "title_en": "UPI fraud — receiving money needs no PIN", "title_hi": "UPI ठगी — पैसे पाने हेतु PIN नहीं लगता",
 "body_en": "To RECEIVE money on UPI you never enter a PIN — any 'approve to receive' request is fraud. Common traps: fake buyer QR codes, screen-sharing apps, 'refund' links, courier-payment scams. Rule: PIN is only for PAYING. If someone rushes you, stop and call 1930. Watch out: fraudsters pose as army buyers, customer care, and even SEBI officials.",
 "body_hi": "UPI पर पैसे पाने हेतु कभी PIN नहीं डालते — 'पाने हेतु अप्रूव करें' वाली हर मांग ठगी है। आम जाल: नकली खरीदार QR, स्क्रीन-शेयरिंग ऐप, 'रिफंड' लिंक, कूरियर-पेमेंट ठगी। नियम: PIN सिर्फ़ देने हेतु है। कोई जल्दी कराए तो रुकें और 1930 पर कॉल करें। सावधान: ठग आर्मी खरीदार, कस्टमर केयर, यहां तक कि SEBI अधिकारी बनते हैं।"},
{"id": "fo_risks", "links": ["https://www.sebi.gov.in", "https://www.nseindia.com"],
 "title_en": "F&O trading — 9 out of 10 lose money", "title_hi": "F&O ट्रेडिंग — 10 में से 9 को नुकसान",
 "body_en": "SEBI's own study: 9 out of 10 individual F&O traders lose money. Futures and options use leverage — small moves cause big losses, fast. Tips sellers profit from your brokerage and fees, not your success. Beginners should learn with cash equity or mutual funds first, with money they can afford to lose. Watch out: 'zero-loss option strategy' courses are marketing, not education.",
 "body_hi": "SEBI के अध्ययन अनुसार 10 में से 9 F&O ट्रेडर पैसे गंवाते हैं। फ्यूचर-ऑप्शन में लीवरेज होता है — छोटी हलचल बड़ा नुकसान, तेज़ी से। टिप बेचने वाले आपकी ब्रोकरेज से कमाते हैं, आपकी जीत से नहीं। शुरुआत कैश शेयर या म्यूचुअल फंड व उतने पैसे से करें जितना गंवाना सह सकें। सावधान: 'ज़ीरो-लॉस ऑप्शन स्ट्रैटेजी' कोर्स मार्केटिंग हैं, शिक्षा नहीं।"},
{"id": "mutual_funds", "links": ["https://www.amfiindia.com"],
 "title_en": "Mutual funds — basics", "title_hi": "म्यूचुअल फंड — बुनियादी बातें",
 "body_en": "A mutual fund pools money from many investors to buy many stocks or bonds, managed by professionals. Costs (expense ratio) eat returns every year — lower is usually better for index funds. 'Direct' plans cost less than 'regular' plans; the difference compounds hugely over decades. Watch out: past returns shown in ads never guarantee future returns.",
 "body_hi": "म्यूचुअल फंड कई निवेशकों का पैसा जोड़कर कई शेयर/बॉन्ड खरीदता है, पेशेवर प्रबंधन के साथ। लागत (एक्सपेंस रेशियो) हर साल रिटर्न खाती है — इंडेक्स फंड हेतु कम बेहतर। 'डायरेक्ट' प्लान 'रेगुलर' से सस्ते होते हैं; दशकों में अंतर बहुत बड़ा होता है। सावधान: विज्ञापनों का पिछला रिटर्न भविष्य की गारंटी नहीं।"},
{"id": "insurance_investment", "links": ["https://www.irdai.gov.in"],
 "title_en": "Insurance is not investment", "title_hi": "बीमा निवेश नहीं है",
 "body_en": "Insurance (term plan) protects your family if you die; investment grows money. Mixed products (ULIPs, endowment plans) usually do BOTH badly — high charges, low cover, poor returns. Keep them separate: pure term insurance + separate investments. Watch out: agents pushing 'insurance with great returns' earn the highest commissions on those products.",
 "body_hi": "बीमा (टर्म प्लान) आपके बाद परिवार की रक्षा करता है; निवेश पैसा बढ़ाता है। मिले-जुले उत्पाद (ULIP, एंडोमेंट) अक्सर दोनों में खराब — ज़्यादा शुल्क, कम कवर, खराब रिटर्न। अलग रखें: शुद्ध टर्म बीमा + अलग निवेश। सावधान: 'बढ़िया रिटर्न वाला बीमा' बेचने पर एजेंट को सबसे ज़्यादा कमीशन मिलता है।"},
{"id": "loan_trap", "links": ["https://www.rbi.org.in"],
 "title_en": "Loan traps — borrowing to invest", "title_hi": "कर्ज़ का जाल — उधार लेकर निवेश",
 "body_en": "Borrowing (personal loans, instant-loan apps) to trade or invest means losses come with interest attached. Instant-loan apps may charge 30-60% yearly and harass contacts on default. Never invest emergency savings or borrowed money in markets. Watch out: 'instant approval, no documents' lenders and 'trade with our funding' offers.",
 "body_hi": "ट्रेड/निवेश हेतु उधार (पर्सनल लोन, इंस्टेंट-लोन ऐप) यानी नुकसान के साथ ब्याज़ भी। इंस्टेंट-लोन ऐप सालाना 30-60% वसूल सकते हैं और डिफॉल्ट पर संपर्कों को परेशान करते हैं। आपात बचत या उधार का पैसा बाज़ार में कभी न लगाएं। सावधान: 'तुरंत अप्रूवल, बिना दस्तावेज़' कर्ज़दाता व 'हमारे पैसे से ट्रेड करो' ऑफर।"},
]
